spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
     matching-strategy: ant_path_matcher

logging:
  level:
    com.unical.solarVision.core: DEBUG

server:
  servlet:
    context-path: /api
  error:
    include-message: always

security:
  secret: chiavedacambiare
  prefix: 'Bearer '
  param: Authorization

admin:
  email: admin@test.com
  password: test

